---
on: 
  push:
    paths-ignore:
      - 'README.md'
      - '.gitlab-ci.yaml'
  workflow_dispatch:
    inputs:
      site:
        type: choice
        description: website to test
        options: 
        - 'https://flowcv.me/sebastian-neubert-2k'

name: 'Cypress tests'
run-name: '${{ github.actor }} pushed "${{ github.event.head_commit.message }}" 🚀'

jobs:
  cypress-test-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_SITE_UNDER_TEST: ${{ github.event.inputs.site }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - run: 'bun install'
      - run: 'bun x cypress run'
      - name: Store HTML report
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: cypress/reports/html/index.html
#
#  deploy:
#    needs: cypress-test-run
#    if: github.ref == 'refs/heads/main'
#
#    permissions:
#      pages: write
#      id-token: write
#
#    # Deploy to the github-pages environment
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#
#    # Specify runner + deployment step
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4